(* Witness generation: turn a finding into a program that demonstrates it.

   We do NOT prove a finding by parsing a crash message: the runtime prints the
   effect payload only sometimes (docs/TYPEDTREE-NOTES.md §7). Instead the
   witness installs a handler for exactly the effect under suspicion and
   reports a positive confirmation when that effect arrives:

     match ignore (Target.f args) with
     | () -> print_endline "NOT_CONFIRMED"
     | effect (Target.Eff _), _ -> print_endline "CONFIRMED"

   Reaching that handler proves the effect escaped the callee unhandled, which
   is precisely the claim being made. *)

type outcome =
  | Confirmed                    (* the effect arrived at our handler *)
  | Confirmed_by_crash           (* the program died with Effect.Unhandled *)
  | Not_confirmed                (* ran cleanly: the finding is suspect *)
  | Not_constructible of string  (* we could not build a witness, and say so *)
  | Build_failed of string

let string_of_outcome = function
  | Confirmed -> "confirmed"
  | Confirmed_by_crash -> "confirmed (crash)"
  | Not_confirmed -> "NOT CONFIRMED"
  | Not_constructible r -> "not constructible: " ^ r
  | Build_failed r -> "build failed: " ^ r

(* ------------------------------------------------- type-directed synthesis *)

(* Values are deliberately non-trivial: an empty list would make
   [List.iter f []] perform nothing and the witness would prove nothing. *)
let rec synth (ty : Types.type_expr) : string option =
  match Types.get_desc ty with
  | Types.Tlink t -> synth t
  | Types.Tsubst (t, _) -> synth t
  | Types.Tpoly (t, _) -> synth t
  | Types.Ttuple ts ->
      let parts = List.map synth ts in
      if List.exists (fun x -> x = None) parts then None
      else Some ("(" ^ String.concat ", " (List.map Option.get parts) ^ ")")
  | Types.Tconstr (p, args, _) -> (
      match (Path.name p, args) with
      | "unit", _ -> Some "()"
      | "int", _ -> Some "1"
      | "bool", _ -> Some "true"
      | "float", _ -> Some "1.0"
      | "char", _ -> Some "'w'"
      | "string", _ -> Some "\"witness\""
      | "list", [ a ] -> Option.map (fun v -> "[" ^ v ^ "]") (synth a)
      | "array", [ a ] -> Option.map (fun v -> "[|" ^ v ^ "|]") (synth a)
      | "option", [ a ] -> Option.map (fun v -> "(Some " ^ v ^ ")") (synth a)
      | _ -> None)
  | _ -> None

let rec params ty acc =
  match Types.get_desc ty with
  | Types.Tarrow (_, a, b, _) -> params b (a :: acc)
  | Types.Tlink t -> params t acc
  | _ -> List.rev acc

(* ----------------------------------------------------------------- emitter *)

let source ~target ~args ~effect_name ~arity =
  let pat = if arity = 0 then effect_name else effect_name ^ " _" in
  Printf.sprintf
    "(* Generated by unhandled. Proves that %s escapes %s unhandled. *)\n\
     let () =\n\
    \  match ignore (%s %s) with\n\
    \  | () -> print_endline \"NOT_CONFIRMED\"\n\
    \  | effect (%s), _ -> print_endline \"CONFIRMED\"\n"
    effect_name target target (String.concat " " args) pat

let generate ~(nodes : Builder.node list) ~arities (f : Report.finding) =
  match f.Report.f_kind with
  | Report.Unknown_effects -> Error "finding has no specific effect"
  | Report.Scheduler_mismatch _ ->
      Error "scheduler mismatch: witness needs the real runtime installed"
  | Report.Escapes eff -> (
      match List.find_map (fun s -> s.Solver.st_callee) f.Report.f_path with
      | None -> Error "no named function in the blame path"
      | Some target -> (
          match
            List.find_opt (fun (n : Builder.node) -> n.Builder.name = target) nodes
          with
          | None -> Error ("no summary for " ^ target)
          | Some nd -> (
              match nd.Builder.ntype with
              | None -> Error "callee type unavailable"
              | Some ty -> (
                  let ps = params ty [] in
                  if ps = [] then Error (target ^ " is not a function")
                  else
                    let vs = List.map synth ps in
                    if List.exists (fun x -> x = None) vs then
                      Error "argument type not synthesisable"
                    else
                      let arity =
                        match
                          List.find_opt (fun (e, _) -> Effect_id.equal e eff) arities
                        with
                        | Some (_, a) -> a
                        | None -> 0
                      in
                      Ok
                        ( target,
                          source ~target ~args:(List.map Option.get vs)
                            ~effect_name:(Effect_id.to_string eff) ~arity )))))

(* ------------------------------------------------------- compile and verify *)

(* Run a shell command, capturing output. Uses Sys.command + a temp file so
   the library needs no external dependencies. *)
let read_process cmd =
  let tmp = Filename.temp_file "unhandled" ".out" in
  let rc = Sys.command (Printf.sprintf "%s > %s 2>&1" cmd (Filename.quote tmp)) in
  let out =
    try
      let ic = open_in_bin tmp in
      let n = in_channel_length ic in
      let s = really_input_string ic n in
      close_in ic; s
    with _ -> ""
  in
  (try Sys.remove tmp with _ -> ());
  (out, rc)

let quote = Filename.quote

(* Build the witness together with the sources of the units under analysis and
   run it. Deliberately sandboxed in its own directory and time-limited. *)
let verify ~ocamlc ~runner ~dir ~sources ~witness_src =
  let wfile = Filename.concat dir "unhandled_witness.ml" in
  let oc = open_out wfile in
  output_string oc witness_src;
  close_out oc;
  let srcs = List.map (fun s ->
      let base = Filename.basename s in
      let dst = Filename.concat dir base in
      (try
         let ic = open_in_bin s and oc = open_out_bin dst in
         let n = in_channel_length ic in
         output_string oc (really_input_string ic n);
         close_in ic; close_out oc
       with _ -> ());
      base) sources
  in
  let exe = "unhandled_witness_exe" in
  let cmd =
    Printf.sprintf "cd %s && %s -o %s %s unhandled_witness.ml" (quote dir) ocamlc
      exe (String.concat " " (List.map quote srcs))
  in
  let out, st = read_process cmd in
  match st with
  | 0 -> (
      let runcmd =
        Printf.sprintf "cd %s && timeout 10 %s ./%s" (quote dir) runner exe
      in
      let rout, rst = read_process runcmd in
      let has s sub =
        let n = String.length sub in
        let rec go i = i + n <= String.length s && (String.sub s i n = sub || go (i + 1)) in
        go 0
      in
      match rst with
      | 0 when has rout "CONFIRMED" && not (has rout "NOT_CONFIRMED") -> Confirmed
      | 0 when has rout "NOT_CONFIRMED" -> Not_confirmed
      | _ when has rout "Effect.Unhandled" -> Confirmed_by_crash
      | _ -> Not_confirmed)
  | _ -> Build_failed (String.trim (String.sub out 0 (min 200 (String.length out))))
