#!/usr/bin/env bash
# Derive the sweep corpus from opam instead of from memory.
#
# bench/repos.txt started as a hand-written list, which has two problems. It is
# small, and it is a list of projects someone happened to think of -- so a
# finding rate computed over it is a finding rate over one person's recall. The
# reproducible question is: of every published package that depends on an
# effect scheduler, how many does the analyser have something to say about?
#
#   bash bench/discover.sh > bench/repos.generated.txt
#   REPOS_FILE=bench/repos.generated.txt bash bench/sweep.sh
#
# Anything with no dev-repo field, or a dev-repo we cannot reach, is dropped
# here and counted, because a corpus that silently loses members inflates every
# rate computed over it.
set -uo pipefail

DEPS="${DEPS:-eio eio_main picos domainslib riot moonpool miou}"
command -v opam >/dev/null || { echo "FATAL: opam not found." >&2; exit 2; }

pkgs=""
for d in $DEPS; do
  # -A asks the whole repository rather than the current switch.
  found="$(opam list -A --depends-on "$d" --short 2>/dev/null)"
  [ -n "$found" ] && pkgs="$pkgs $found"
  echo "# $d: $(echo "$found" | grep -c . ) dependent package(s)" >&2
done

# Package name -> dev-repo, deduplicated by URL: many opam packages ship from
# one repository (eio alone publishes eio, eio_main, eio_posix, eio_linux) and
# cloning it four times would count it four times in the denominator.
seen_urls=""
n_pkgs=0; n_norepo=0; n_emitted=0

echo "# Generated by bench/discover.sh on $(date -u +%Y-%m-%dT%H:%MZ)"
echo "# Corpus: every opam package depending on one of: $DEPS"
echo "# Format: <name> <git-url> [subdirectory]"
echo

for p in $(echo "$pkgs" | tr ' ' '\n' | sed 's/\..*//' | sort -u); do
  [ -z "$p" ] && continue
  n_pkgs=$((n_pkgs+1))
  url="$(opam show --field dev-repo: "$p" 2>/dev/null \
         | tr -d '"' | sed 's/^git+//; s/^ *//; s/ *$//')"
  case "$url" in
    ''|none) n_norepo=$((n_norepo+1)); continue;;
    *github.com*|*gitlab.com*|*git.*) ;;
    *) n_norepo=$((n_norepo+1)); continue;;
  esac
  case " $seen_urls " in *" $url "*) continue;; esac
  seen_urls="$seen_urls $url"
  printf "%-24s %s\n" "$p" "$url"
  n_emitted=$((n_emitted+1))
done

echo >&2
echo "# packages depending on an effect scheduler: $n_pkgs" >&2
echo "# dropped, no usable dev-repo:               $n_norepo" >&2
echo "# repositories emitted (deduplicated):       $n_emitted" >&2
